// Generated by @nuxtjs/sitemap

declare module 'nitropack' {
  interface PrerenderRoute {
    _sitemap?: import('../../node_modules/.pnpm/@nuxtjs+sitemap@7.0.1_h3@1.13.0_magicast@0.3.5_rollup@4.30.1_vite@6.0.7_@types+node@22.10.5_j_c2ofwwvhgec6xwv3sb5mmrbci4/node_modules/@nuxtjs/sitemap/runtime/types').SitemapUrl
  }
  interface NitroRouteRules {
    index?: boolean
    sitemap?: import('../../node_modules/.pnpm/@nuxtjs+sitemap@7.0.1_h3@1.13.0_magicast@0.3.5_rollup@4.30.1_vite@6.0.7_@types+node@22.10.5_j_c2ofwwvhgec6xwv3sb5mmrbci4/node_modules/@nuxtjs/sitemap/runtime/types').SitemapItemDefaults
  }
  interface NitroRouteConfig {
    index?: boolean
    sitemap?: import('../../node_modules/.pnpm/@nuxtjs+sitemap@7.0.1_h3@1.13.0_magicast@0.3.5_rollup@4.30.1_vite@6.0.7_@types+node@22.10.5_j_c2ofwwvhgec6xwv3sb5mmrbci4/node_modules/@nuxtjs/sitemap/runtime/types').SitemapItemDefaults
  }
  interface NitroRuntimeHooks {
    'sitemap:index-resolved': (ctx: import('../../node_modules/.pnpm/@nuxtjs+sitemap@7.0.1_h3@1.13.0_magicast@0.3.5_rollup@4.30.1_vite@6.0.7_@types+node@22.10.5_j_c2ofwwvhgec6xwv3sb5mmrbci4/node_modules/@nuxtjs/sitemap/runtime/types').SitemapIndexRenderCtx) => void | Promise<void>
    'sitemap:resolved': (ctx: import('../../node_modules/.pnpm/@nuxtjs+sitemap@7.0.1_h3@1.13.0_magicast@0.3.5_rollup@4.30.1_vite@6.0.7_@types+node@22.10.5_j_c2ofwwvhgec6xwv3sb5mmrbci4/node_modules/@nuxtjs/sitemap/runtime/types').SitemapRenderCtx) => void | Promise<void>
    'sitemap:output': (ctx: import('../../node_modules/.pnpm/@nuxtjs+sitemap@7.0.1_h3@1.13.0_magicast@0.3.5_rollup@4.30.1_vite@6.0.7_@types+node@22.10.5_j_c2ofwwvhgec6xwv3sb5mmrbci4/node_modules/@nuxtjs/sitemap/runtime/types').SitemapOutputHookCtx) => void | Promise<void>
  }
}
declare module 'vue-router' {
    interface RouteMeta {
        sitemap?: import('../../node_modules/.pnpm/@nuxtjs+sitemap@7.0.1_h3@1.13.0_magicast@0.3.5_rollup@4.30.1_vite@6.0.7_@types+node@22.10.5_j_c2ofwwvhgec6xwv3sb5mmrbci4/node_modules/@nuxtjs/sitemap/runtime/types').SitemapItemDefaults
    }
}

export {}
