// Generated by nuxt-schema-org

declare module '@nuxt/schema' {
  export interface RuntimeNuxtHooks {
    'schema-org:meta': (meta: import('../../node_modules/.pnpm/nuxt-schema-org@4.0.4_@unhead+vue@1.11.15_vue@3.5.13_typescript@5.7.3___magicast@0.3.5_rollup_dh7q3a2glo3u2oihey36q56rn4/node_modules/nuxt-schema-org/dist/runtime/types').MetaInput) => void | Promise<void>
  }
}
declare module '#app' {
  export interface RuntimeNuxtHooks {
    'schema-org:meta': (meta: import('../../node_modules/.pnpm/nuxt-schema-org@4.0.4_@unhead+vue@1.11.15_vue@3.5.13_typescript@5.7.3___magicast@0.3.5_rollup_dh7q3a2glo3u2oihey36q56rn4/node_modules/nuxt-schema-org/dist/runtime/types').MetaInput) => void | Promise<void>
  }
}

export {}
