// Generated by nuxt-robots

declare module 'nitropack' {
  interface NitroApp {
    _robots: {
      ctx: import('../../node_modules/.pnpm/@nuxtjs+robots@5.1.0_magicast@0.3.5_rollup@4.30.1_vite@6.0.7_@types+node@22.10.5_jiti@2.4.2_l_4pvawsqfpqevgq4zkcowlhve5i/node_modules/@nuxtjs/robots/dist/runtime/types').HookRobotsConfigContext
      nuxtContentUrls?: Set<string>
    },
    _robotsRuleMactcher: (url: string) => string
  }
  interface NitroRouteRules {
    robots?: boolean | string | {
      indexable: boolean
      rule: string
    }
  }
  interface NitroRouteConfig {
    robots?: boolean | string | {
      indexable: boolean
      rule: string
    }
  }
  interface NitroRuntimeHooks {
    'robots:config': (ctx: import('../../node_modules/.pnpm/@nuxtjs+robots@5.1.0_magicast@0.3.5_rollup@4.30.1_vite@6.0.7_@types+node@22.10.5_jiti@2.4.2_l_4pvawsqfpqevgq4zkcowlhve5i/node_modules/@nuxtjs/robots/dist/runtime/types').HookRobotsConfigContext) => void | Promise<void>
    'robots:robots-txt': (ctx: import('../../node_modules/.pnpm/@nuxtjs+robots@5.1.0_magicast@0.3.5_rollup@4.30.1_vite@6.0.7_@types+node@22.10.5_jiti@2.4.2_l_4pvawsqfpqevgq4zkcowlhve5i/node_modules/@nuxtjs/robots/dist/runtime/types').HookRobotsTxtContext) => void | Promise<void>
  }
}
declare module 'h3' {
  interface H3EventContext {
    robots: {
      rule: string
      indexable: boolean
    }
  }
}

export {}
